# Generated by Django 6.1.1 on 2026-09-04 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_groupleader'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('fleet_size', models.IntegerField(default=1)),
                ('rate_per_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trust_rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('transport_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transportcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('cargo_weight_kg', models.IntegerField()),
                ('estimated_distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Company Approval'), ('ACCEPTED', 'Accepted - Awaiting Advance'), ('ADVANCE_PAID', 'Advance Paid - Truck Released'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered - Awaiting Verification'), ('COMPLETED', 'Completed & Final Payment Escrow Released')], default='PENDING', max_length=20)),
                ('is_off_platform_booking', models.BooleanField(default=False)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.driver')),
                ('group_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groupleader')),
                ('transport_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transportcompany')),
            ],
        ),
    ]
