# Generated by Django 6.1.1 on 2026-09-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transportcompany_driver_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('SELL', 'Group Leader Selling'), ('BUY', 'Buyer Looking for Crops')], max_length=4)),
                ('poster_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('crop_names', models.CharField(max_length=255)),
                ('quantity_kg', models.IntegerField(help_text='Expected quantity in KG')),
                ('ai_suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=200, null=True)),
                ('needed_by_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
