from django.urls import path
from . import views

urlpatterns = [
    path('onboard-farmer/', views.onboard_farmer, name='onboard_farmer'),
    path('register-leader/', views.register_leader, name='register_leader'),
    path('login-leader/', views.login_leader, name='login_leader'),
    path('get-farmers/', views.get_farmers, name='get_farmers'),
    path('log-harvest/', views.log_harvest, name='log_harvest'),
    path('dashboard-metrics/', views.get_dashboard_metrics, name='dashboard_metrics'),
    path('register-company/', views.register_company, name='register_company'),
    path('login-company/', views.login_company, name='login_company'),
    path('register-driver/', views.register_driver, name='register_driver'),
    path('get-companies/', views.get_companies, name='get_companies'),
    path('login-driver/', views.login_driver, name='login_driver'),
    path('get-marketplace/', views.get_marketplace, name='get_marketplace'),
    path('book-trip/', views.book_trip, name='book_trip'),
    path('get-company-trips/<int:company_id>/', views.get_company_trips, name='get_company_trips'),
    path('get-company-drivers/<int:company_id>/', views.get_company_drivers, name='get_company_drivers'),
    path('accept-trip/', views.accept_trip, name='accept_trip'),
    path('get-pending-escrow/<int:leader_id>/', views.get_pending_escrow, name='get_pending_escrow'),
    path('pay-escrow-advance/', views.pay_escrow_advance, name='pay_escrow_advance'),
    path('get-driver-active-trip/<int:driver_id>/', views.get_driver_active_trip, name='get_driver_active_trip'),
    path('start-transit/', views.start_transit, name='start_transit'),
    path('change-password/', views.change_password, name='change_password'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('complete-delivery/', views.complete_delivery, name='complete_delivery'),
    path('get-final-settlements/<int:leader_id>/', views.get_final_settlements, name='get_final_settlements'),
    path('release-final-escrow/', views.release_final_escrow, name='release_final_escrow'),
    path('create-market-post/', views.create_market_post, name='create_market_post'),
    path('get-market-posts/', views.get_market_posts, name='get_market_posts'),
    path('forecast-price/', views.forecast_price, name='forecast_price'),
    path('update-payment/', views.update_payment, name='update_payment'),
    path('verify-delivery/', views.verify_delivery, name='verify_delivery'),
]